name: Touch Issue
description: Report an issue with Touch with Tinker
labels: [touch]
assignees: Alphalaneous
body: 
  - type: markdown
    attributes:
      value: |
        ## Report an issue with Touch

  - type: input
    id: tinker-version
    attributes: 
      label: Tinker version
      description: The version of Tinker you are currently using.
      placeholder: The version number (such as v1.0.0-beta.14)
    validations:
      required: true

  - type: input
    id: geode-version
    attributes: 
      label: Geode version
      description: The version of Geode you are currently using.
      placeholder: The version number (such as v5.5.3)
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Information
      description: Where does touch break? What did you do before this happened? Please provide steps if you can replicate.
    validations:
      required: true

  - type: textarea
    id: mod-list
    attributes:
      label: Mod List
      description: |
        What mods do you have installed?
        You can copy the mod list in Geode Settings by clicking "Copy Mods"
    validations:
      required: true